version: "3.1"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: deployer-node
    image: rebelinblue/deployer-node:latest
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/node/supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - "6001:6001"
    links:
      - redis

  beanstalkd:
    image: schickling/beanstalkd
    container_name: deployer-beanstalkd
    ports:
      - "11300:11300"

  redis:
    image: phpdockerio/redis:latest
    container_name: deployer-redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: deployer-worker
    image: rebelinblue/deployer-worker:latest
    volumes:
      - .:/application
      - ./docker/worker/supervisord.conf:/etc/supervisord.conf
    links:
      - beanstalkd
      - redis
